<a href="https://colab.research.google.com/github/vishalmmca25-design/ml-and-datavisualization/blob/main/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

History Numpy
• Numpy stands for Numerical Python

• It is the fundamental python library to perfrom complex numerical operations

• Numpy is developed on top of Numeric library in 2005.

• Numeric library developed by Jim Hugunin.

• Numpy is developed by Travis Oliphant and mutiple contributors

• Numpy is freeware and open source library

• Numpy library is written in C and Python

• C language ==> performance is very high

• Most of Numpy is written in C, So performance-wise Numpy is the best

• Because of high speed, numpy is best choice for ML algorithms than traditional

python's in-built data structures like List.

But in Python, we can create arrays in the following 2 ways:

• By using array module

• By using numpy module

To install latest version

 pip install numpy

to install particular version of numpy

 pip install numpy==1.20.0


In [ ]:
# Check the version of Numpy installed
import numpy as np
print(np.__version__)

2.0.2


Performance Test:

In [ ]:
import numpy as np
from datetime import datetime
a = np.array([10,20,30])
b = np.array([1,2,3])
#dot product: A.B=10X1 + 20X2 +30X3=140
#traditional python code
def dot_product(a,b):
  result = 0
  for i,j in zip(a,b):
    result = result + i*j
  return result
before = datetime.now()
for i in range(1000000):
  dot_product(a,b)
after = datetime.now()
print('The Time taken by traditonal python:',after-before)
#numpy library code
before = datetime.now()
for i in range(1000000):
  np.dot(a,b) # this is from numpy
after = datetime.now()
print('The Time taken by Numpy Library:',after-before)


The Time taken by traditonal python: 0:00:02.012799
The Time taken by Numpy Library: 0:00:01.880742


Python List Vs Numpy Array
Similarities:
1. Both can be used to store data
2. The order will be preserved in both. Hence indexing and slicing concepts are
applicable.
3. Both are mutable, ie we can change the content.

Differences:

1. list is python's inbuilt type. we have to install and import numpy explicitly.

2. List can contain heterogeneous elements. But array contains only homogeneous
elements.

3. On list, we cannot perform vector operations. But on ndarray we can perform vector
operations.
4. Arrays consume less memory than list.
5. Arrays are superfast when compared with list.
6. Numpy arrays are more convenient to use while performing complex mathematical
operations

In [ ]:
# 3. On list, we cannot perform vector operations.
# But on ndarray we can perform vector operations.
import numpy as np
l1 = [10,20,30,40]
a1 = np.array([10,20,30,40])
l1+2 # not possible


TypeError: can only concatenate list (not "int") to list

In [ ]:
# On ndarrays we can perform vector operations
import numpy as np
a1 = np.array([10,20,30,40])
a1+2 # array([12,22,32,42])


array([12, 22, 32, 42])

**Creation of Numpy Arrays**

Array (ndarray) creation using Numpy
1. array()
2. arange()
3. linspace()
4. zeros()
5. ones()
6. full()
7. eye()
8. identity()
9. diag()
10. empty()

In [ ]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

1-D array(Vector) creation using list or tuple

In [ ]:
# 1-D array creation from list or tuple
l = [10,20,30]
print(f'Type of l ==> {type(l)}')
a = np.array(l)
print(f'Type of a ==> {type(a)}')
print(f"a ==> {a}")


Type of l ==> <class 'list'>
Type of a ==> <class 'numpy.ndarray'>
a ==> [10 20 30]


To know properties of ndarray

• np.ndim ==> to know the dimension of the ndarray

• np.dtype ==> to know the data type of the elements in the ndarray

• np.size ==> to know the total number of elements in the array.

• np.shape ==> returns the shape of an array in tuple form


In [ ]:
# properties of ndarray
print(f'The dimensions of the array a ==> {a.ndim}')
print(f'The data type of elements of array a ==> {a.dtype}')
print(f'The size of the array a ==> {a.size}')
print(f'The shape of the array a ==> {a.shape}')


The dimensions of the array a ==> 1
The data type of elements of array a ==> int64
The size of the array a ==> 3
The shape of the array a ==> (3,)


In [ ]:
# 1-D array creating using tuples
t = ('krishna','nandu','moneesh')
print(f'Type of t ==> {type(t)}')
a = np.array(t)
print(f'Type of a ==> {type(a)}')
print(f'The data type of elements of array a ==> {a.dtype}')
print(f'The size of the array a ==> {a.size}')
print(f'The shape of the array a ==> {a.shape}')
print(f"a ==> {a}")


Type of t ==> <class 'tuple'>
Type of a ==> <class 'numpy.ndarray'>
The data type of elements of array a ==> <U7
The size of the array a ==> 3
The shape of the array a ==> (3,)
a ==> ['krishna' 'nandu' 'moneesh']


2-D array(Matrix) creation using Nested Lists

In [ ]:
# [[10,20,30],[40,50,60],[70,80,90]] --->Nested List
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(f'Type of a ==> {type(a)}')
print(f'a ==> \n {a}')
print(f'The dimensions of the array a ==> {a.ndim}')
print(f'The data type of elements of array a ==> {a.dtype}')
print(f'The size of the array a ==> {a.size}')
print(f'The shape of the array a ==> {a.shape}')

Type of a ==> <class 'numpy.ndarray'>
a ==> 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
The dimensions of the array a ==> 2
The data type of elements of array a ==> int64
The size of the array a ==> 9
The shape of the array a ==> (3, 3)


Note:

• Array contains only homogenous elements

• If list contains heterogenous elements, and while creating the array upcasting will be performed.

In [ ]:
# list contains heterogenous elements
l = [10,20,30.5]
a = np.array(l) # upcasting to float
print(f'a :: {a}')
print(f'data type of elements of a ==> {a.dtype}')

a :: [10.  20.  30.5]
data type of elements of a ==> float64


Creating arrays with particular datatype

• we have to use dtype argument while creating the arrray

In [ ]:
# int type
a = np.array([10,20,30.5],dtype=int)
print(a)

[10 20 30]


In [ ]:
# float type
a = np.array([10,20,30.5],dtype=float)
print(a)

[10.  20.  30.5]


arange()

• we can create only 1-D arrays with arange() function

In [ ]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.

    See the Warn

Python:
1. range(n) ==> n values from 0 to n-1
 range(4) ==> 0,1,2,3
2. range(m,n)==> from m to n-1
 range(2,7)==> 2,3,4,5,6
3. range(begin,end,step)

 range(1,11,1) ==> 1,2,3,4,5,6,7,8,9,10

 range(1,11,2) ==> 1,3,5,7,9

 range(1,11,3) ==> 1,4,7,10

In [ ]:
# only stop value ==> 0 to stop-1
import numpy as np
a = np.arange(10)
print(f'a ==> {a}')
print(f'The dimensions of the array a ==> {a.ndim}')
print(f'The data type of elements of array a ==> {a.dtype}')
print(f'The size of the array a ==> {a.size}')
print(f'The shape of the array a ==> {a.shape}')

a ==> [0 1 2 3 4 5 6 7 8 9]
The dimensions of the array a ==> 1
The data type of elements of array a ==> int64
The size of the array a ==> 10
The shape of the array a ==> (10,)


linspace()

• same as arange() only but in the specified interval, linearly spaced values

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

• Both start and stop are includded because endpoint=True

• If endpoint=False then stop is excluded

• retstep denotes the spacing between the points.If True then the value is returned

• calculation of spacing (stop-start)/(num-1) if endpoint=True

• calculation of spacing (stop-start)/(num) if endpoint=False


In [ ]:
# 50 evenly spaced values between 0 and 1 are returned including both 0 and 1
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [ ]:
# 4 evenly spaced valued between 0 and 1 including 0 and 1
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
# 4 evenly spaced valued between 0 and 1 including 0 and excluding 1
np.linspace(0,1,4,endpoint=False)

array([0.  , 0.25, 0.5 , 0.75])

In [ ]:
# 4 evenly spaced valued between 0 and 1 including 0 and excluding 1 and return spacing
np.linspace(0,1,4,endpoint=False,retstep=True)

(array([0.  , 0.25, 0.5 , 0.75]), np.float64(0.25))

zeros
• array is filled with 0s


• 0-D array ==> Scalar :: single value
• 1-D array ==> Vector :: Collection of 0-D arrays
• 2-D array ==> Matrix :: Collection of 1-D arrays
• 3-D array ==> collcetion of 2-D arrays
• (10,) ==>1-D array contains 10 elements
• (5,2) ==>2-D array contains 5 rows and 2 columns
• (2,3,4) ==>3-D array

   2 ==> number of 2-D arrays

   3 ==> The number of rows in every 2-D array

   4 ==> The number of columns in every 2-D array
  
   size: 2* 3* 4 = 24

In [ ]:
# 1-D array with zeros
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
# 2-D arrays with zeros
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# 3-D array
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

ones()
• exactly same as zeros except array is filled with 1

In [ ]:
# 1-D array
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

full
• Return a new array of given shape and type, filled with fill_value

In [ ]:
# 1-D array
np.full(10,fill_value=2)


array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# 2-D array
np.full((2,3),fill_value=3)

array([[3, 3, 3],
       [3, 3, 3]])

eye()

• To generate identity matrix

• Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [ ]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

empty()
• Return a new array of given shape and type, without initializing entries

In [ ]:
np.empty((3,3))


array([[4.94e-323, 9.88e-323, 1.48e-322],
       [1.98e-322, 2.47e-322, 2.96e-322],
       [3.46e-322, 3.95e-322, 4.45e-322]])

zeros() vs empty()
1. If we required an array only with zeros then we should go for zeros().
2. If we never worry about data, just we required an empty array for future purpose,
then we should go for empty().
3. The time required to create emtpy array is very very less when compared with
zeros array. i.e performance wise empty() function is recommended than zeros() if
we are not worry about data

np.random module
• This library contains several functions to create nd arrays with random data.


randint
• To generate random int values in the given range


randint(low, high=None, size=None, dtype=int)

• Return random integers from low (inclusive) to high (exclusive).

• it is represented as [low, high) ==> [ means inclusive and ) means exclusive

• If high is None (the default), then results are from [0, low)

In [ ]:
# it will generate a single random int value in the range 10 to 19.
np.random.randint(10,20)

19

In [ ]:
# To create 1-D ndarray of size 10 with random values from 1 to 8?
np.random.randint(1,9,size=10)

array([5, 2, 4, 1, 7, 2, 6, 5, 5, 3])

In [ ]:
# To create 2D array with shape(3,5)
np.random.randint(100,size=(3,5))

array([[27, 13, 20, 88, 71],
       [42,  2, 63, 91, 75],
       [15, 57, 78, 56, 39]])

Accessing Elements of ndarray
1. Indexing ==> only one element
2. Slicing ==> group of elements which are in order
3. Advanced indexing ==> group of elements which are not in order(arbitrary
elements)
4. Condition based selection ==> array_name[condition]

Indexing -- only one element

• By using index, we can get/access single element of the array.

• Zero Based indexing. ie the index of first element is 0

• supports both +ve and -ve indexing.


Accessing elements of 1-D array
• 1-D array : array[index]

In [ ]:
# 1-D array
# array[index]
import numpy as np
a = np.array([10,20,30,40,50])
a[3]

np.int64(40)

In [ ]:
# -ve indexing
a[-1]

np.int64(50)

In [ ]:
# 2-D array
# a[rowindex][columnindex]
import numpy as np
a = np.array([[10,20,30],[40,50,60]])
print(f"Shape of the array a : {a.shape}")
print("To Access the element 50")
print(f"a[1][1] ==> {a[1][1]}")
print(f"a[1][-2] ==> {a[1][-2]}")
print(f"a[-1][2] ==> {a[-1][-2]}")
print(f"a[-1][1] ==> {a[-1][1]}")

Shape of the array a : (2, 3)
To Access the element 50
a[1][1] ==> 50
a[1][-2] ==> 50
a[-1][2] ==> 50
a[-1][1] ==> 50


Slicing ==> group of elements which are in order

Python's slice operator:

Syntax-1: l[begin:end]

• It returns elements from begin index to (end-1) index


In [ ]:
l = [10,20,30,40,50,60,70]
l[2:6] #from 2nd index to 5th index


[30, 40, 50, 60]

In [ ]:
# If we are not specifying begin index then default is 0
l[:3] #from 0 index to 2nd index

[10, 20, 30]

Advanced indexing-- group of elements which are not in order (arbitrary
elements)


In [ ]:
a = np.array([10,20,30,40])
boolean_array=np.array([True,False,False,True])
a[boolean_array]

array([10, 40])

In [ ]:
## condition based selection is applicatble for 2-D array also
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# select the even numbers from 2-D array
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

Iterate elements of nd array

We can iterate nd arrays in 3 ways

• 1) By using Python's loops concept

• 2) By using nditer() function

• 3) By using ndenumerate() function


In [ ]:
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
for x in a: #x is 1-D array but not scalar value
  for y in x: # y is scalar value present in 1-D array
    print(y)


10
20
30
40
50
60
70
80
90


In [ ]:
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
for x in np.nditer(a):
 print(x)


10
20
30
40
50
60
70
80
90


By using ndenumerate() function

• By using nditer() we will get elements only but not indexes

• If we want indexes also in addition to elements, then we should use
ndenumerate() function.

• ndenumerate() function returns multidimensional index iterator which yields
pairs of array indexes(coordinates) and values.


In [ ]:
a = np.array([10,20,30,40,50,60,70])
for pos,element in np.ndenumerate(a):
 print(f'{element} element present at index/position:{pos}')


10 element present at index/position:(0,)
20 element present at index/position:(1,)
30 element present at index/position:(2,)
40 element present at index/position:(3,)
50 element present at index/position:(4,)
60 element present at index/position:(5,)
70 element present at index/position:(6,)


Array Manipulation functions

reshape() function
• We can use reshape() function to change array shape without changing data.

In [ ]:
# While using reshape() function, make sure the sizes should be matched otherwise we will get error.
import numpy as np
a = np.arange(1,11)
print(f"array : {a}")
b = np.reshape(a,(5,3))
array : [ 1 2 3 4 5

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3358059459.py, line 6)

In [ ]:
# converting 1-D array to 2-D array
a = np.arange(1,11)
print(f"array : {a}")
b = np.reshape(a,(5,2))
print(f"Converting 1-D(a) array to 2-D(b) array : \n {b} ")

array : [ 1  2  3  4  5  6  7  8  9 10]
Converting 1-D(a) array to 2-D(b) array : 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 


resize()

Syntax:

numpy.resize(a, new_shape)

In [ ]:
a = np.arange(1,6)
b = np.resize(a,(2,4))
print(f"Original array : {a}")
print(f"Reshaped array :\n {b}")

Original array : [1 2 3 4 5]
Reshaped array :
 [[1 2 3 4]
 [5 1 2 3]]


flatten() method

• We can use flatten() method to flatten(convert) any n-Dimensional array to 1-Dimensional array.


In [ ]:
# converting 2-D array to 1-D array ==> C style
a = np.arange(6).reshape(3,2)
b = a.flatten()
print(f"Original array :\n {a}")
print(f"Flatten array :\n {b}")


Original array :
 [[0 1]
 [2 3]
 [4 5]]
Flatten array :
 [0 1 2 3 4 5]


Joining of multiple arrays into a single array
It is similar to Join queries in Oracle
We can join/concatenate multiple ndarrays into a single array by using the following
functions.*
1. concatenate()
2. stack()
3. vstack()
4. hstack()
5. dstack()


In [ ]:
# 1-D array
import numpy as np
a = np.arange(4)
b = np.arange(5)
c = np.arange(3)
np.concatenate((a,b,c))


array([0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2])

In [ ]:
# stacking using axis=0
a = np.array([10,20,30])
b = np.array([40,50,60])
resultant_array = np.stack((a,b)) # default axis=0
print(f"Resultant array : \n {resultant_array}")
print(f"Resultant array shape: {resultant_array.shape}")

Resultant array : 
 [[10 20 30]
 [40 50 60]]
Resultant array shape: (2, 3)


Sorting elements of nd arrays

• We can sort elements of nd array.

• numpy module contains sort() function.

• The default sorting algorithm is quicksort and it is Ascending order

• We can also specify mergesort, heapsort etc

• For numbers-->Ascending order

• For Strings-->alphabetical order

In [ ]:
# 1-D arrays
a = np.array([70,20,60,10,50,40,30])
sorted_array = np.sort(a)
print(f"Original array a : {a}")
print(f"Sorted array(Ascending by default) : {sorted_array}")

Original array a : [70 20 60 10 50 40 30]
Sorted array(Ascending by default) : [10 20 30 40 50 60 70]


How to insert elements into ndarray

• insert() ==> inserting the element at the required position

• append() ==> inserting the element at the end


In [ ]:
# To insert 7777 before index 2
a = np.arange(10)
b = np.insert(a,2,7777)
print(f"array a : {a}")
print(f"array b : {b}")

array a : [0 1 2 3 4 5 6 7 8 9]
array b : [   0    1 7777    2    3    4    5    6    7    8    9]


append()

• By using insert() function, we can insert elements at our required index position.

• If we want to add elements always at end of the ndarray, then we have to go for
append() function.

In [ ]:
# append 100 element to the existing array of int
a = np.arange(10)
b = np.append(a,100)
print(f"array a : {a}")
print(f"array b : {b}")

array a : [0 1 2 3 4 5 6 7 8 9]
array b : [  0   1   2   3   4   5   6   7   8   9 100]


I/O operations with Numpy

• We can save/write ndarray objects to a binary file for future purpose.

• Later point of time, when ever these objects are required, we can read from that binary file.

• save() ==> to save/write ndarry object to a file

• load() ==>to read ndarray object from a file

In [ ]:
a = np.array([[10,20,30],[40,50,60]]) #2-D array with shape:(2,3)
#save/serialize ndarray object to a file
np.save('out.npy',a)
#load/deserialize ndarray object from a file
out_array = np.load('out.npy')
print(out_array)


[[10 20 30]
 [40 50 60]]


Basic Statistics with Numpy

In Datascience domain, we required to collect,store and analyze huge amount of data. From this data we may required to find some basic statistics like
1. Minimum value
2. Maximum value
3. Average Value
4. Sum of all values
5. Mean value
6. Median value
7. Variance
8. Standard deviation etc

In [ ]:
a = np.array([10,5,20,3,25])
print(f"1-D array : {a}")
print(f"np.min(a) value : {np.min(a)}")
print(f"np.amin(a) value : {np.amin(a)}")
print(f"a.min() value : {a.min()}")

1-D array : [10  5 20  3 25]
np.min(a) value : 3
np.amin(a) value : 3
a.min() value : 3


In [ ]:
a = np.array([10,5,20,3,25])
print(f"1-D array : {a}")
print(f"np.max(a) value : {np.max(a)}")
print(f"np.amax(a) value : {np.amax(a)}")
print(f"a.max() value : {a.max()}")

1-D array : [10  5 20  3 25]
np.max(a) value : 25
np.amax(a) value : 25
a.max() value : 25


In [ ]:
# sum of elements of 1-D array
a = np.arange(4)
print(f"The array a : {a}")
print(f"sum of elements using np.sum(a) :: {np.sum(a)}")
print(f"sum of elements using a.sum() :: {a.sum()}")

The array a : [0 1 2 3]
sum of elements using np.sum(a) :: 6
sum of elements using a.sum() :: 6


In [ ]:
a = np.arange(5)
print(f"1-D array : {a}")
print(f"np.mean(a) value : {np.mean(a)}")
print(f"a.mean() value : {a.mean()}")

1-D array : [0 1 2 3 4]
np.mean(a) value : 2.0
a.mean() value : 2.0


Numpy Mathematical Functions

• The functions which operates element by element on whole array, are called universal functions.

• To perform mathematical operations numpy library contains several universalfunctions (ufunc).

1. np.exp(a) --->Takes e to the power of each value. e value: 2.7182
2. np.sqrt(a) --->Returns square root of each value.
3. np.log(a) --->Returns logarithm of each value.
4. np.sin(a) ---->Returns the sine of each value.
5. np.cos(a) --->Returns the co-sine of each value.
6. np.tan(a) --->Returns the tangent of each value.